name: apna_thekedar_specialist
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  geocoding: ^3.0.0
  location: ^5.0.3
  image_picker: ^1.0.7
  flutter_local_notifications: ^17.0.0
  webview_flutter: ^4.7.0
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.6 
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  slide_to_act: ^2.0.2
  intl: ^0.19.0
  flutter_launcher_icons: "^0.13.1"
  web_socket_channel: ^2.4.0
  provider: ^6.0.0 # Aap yahan latest version daal sakte hain
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.0.0
  flutter_compass: ^0.8.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^6.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ # Agar aapke paas logo jaisi koi image hai
    - assets/logo.png
    - assets/logo2.png
    - assets/no_internet.png
    - assets/no_job.png
    - assets/no_jobs.png
    - assets/server_error.png


flutter_launcher_icons:
  android: true       # Android ke liye icon generate karein
  ios: true           # iOS ke liye icon generate karein
  image_path: "assets/icon.png"
